CC = gcc

all: list stack queue

list:
	$(CC) list.c list_demo.c -o list.exe

stack:
	$(CC) list.c stack.c stack_demo.c -o stack.exe

queue:
	$(CC) list.c queue.c queue_demo.c -o queue.exe

clean:
	rm *.exe

