CC = gcc

all: list stack queue bitree

list:
	$(CC) list.c list_demo.c -o list.exe

stack:
	$(CC) list.c stack.c stack_demo.c -o stack.exe

queue:
	$(CC) list.c queue.c queue_demo.c -o queue.exe

bitree:
	$(CC) list.c bitree.c traverse.c bitree_demo.c -o bitree.exe

clean:
	rm *.exe

