include ./Make.defines

all:
	@echo "在当前目录没什么可 make 的"
	@echo "请阅读 README 文件"

clean:
	rm -f $(CLEANFILES)
 
distclean:
	rm -f $(CLEANFILES) config.cache config.log config.status config.h Make.defines Makefile
